#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & # Keyboard shortcuts
picom --experimental-backends & # Compositor
~/.config/polybar/launch.sh & # Status bar
xsetroot -cursor_name left_ptr & # X cursor fix
#dunst & # Notifications


gnome-keyring-daemon --start --components=pkcs11,secret,ssh & #Keyring
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 & 

bspc monitor -d 1 2 3 4 5 6 7 8 9 10        
 
#BSPWM configuration
#bspc config border_radius        10.5
bspc config border_width         3
bspc config window_gap           4
bspc config top_padding          28
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true


#BSPWM coloring
bspc config normal_border_color		"#928374"
bspc config active_border_color		"#928374"
bspc config focused_border_color	"#fb4934"
bspc config presel_feedback_color	"#5e81ac"

#bspc rule -a Termite state=floating follow=on
bspc rule -a Seahorse state=floating follow=on
bspc rule -a Steam desktop='^6' follow=off
bspc rule -a Spotify desktop='^6' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

